### ISSUE TITLE
Implement `config/base.go` and `config/config.go`

### ISSUE THREAD

**Issue by gerceboss** [BlocSoc-iitr/selene#12]

**Comment by 18aaddy** [comment]
Interested

**Comment by 18aaddy** [comment]
@gerceboss for config.go I have to import calculate_fork_version() function from consensus_core/consensus_core.go. So what should I do for that?

**Comment by star-gazer111** [comment]
@18aaddy what is the progress on this issue?

**Comment by 18aaddy** [comment]
I have written both config.go and base.go and have tested both of them. Only one function in config.go is remaining for which I will need to define consesus_core.go

**Comment by star-gazer111** [comment]
Resolved here #26
