### ISSUE TITLE
Implement `config/networks.go`

### ISSUE THREAD

**Issue by gerceboss** [BlocSoc-iitr/selene#13]

**Comment by VeerChaurasia** [comment]
Assign

**Comment by VeerChaurasia** [comment]
@gerceboss should I implement base.go as it contains some field used in networks or should I just import it without implementing?

**Comment by star-gazer111** [comment]
> @gerceboss should I implement base.go as it contains some field used in networks or should I just import it without implementing?

U will have to wait for @18aaddy to open up his PR first & then use the necessary imports from there.

**Comment by star-gazer111** [comment]
> @star-gazer111 as the template doesn't had HOLESKY initially so should I write case for Holesky or not?

You can skip that for now.

**Comment by star-gazer111** [comment]
Resolver here #20
