### ISSUE TITLE
Implement `config/cli.go`

### ISSUE THREAD

**Issue by gerceboss** [BlocSoc-iitr/selene#15]

**Comment by ABD-AZE** [comment]
Assign

**Comment by ABD-AZE** [comment]
which configuration manager should I use in go?? I think VIper is the most famous one, should I go with that?

**Comment by star-gazer111** [comment]
> which configuration manager should I use in go?? I think VIper is the most famous one, should I go with that?

Could've used [tachyon](https://github.com/vektra/tachyon) too but it's not maintained anymore I suppose.
Can you once checkout [store](https://github.com/tucnak/store) & share your views?
@gerceboss any suggestions?

**Comment by ABD-AZE** [comment]
[store](https://github.com/tucnak/store) seems easier to use, I think we should go ahead with it.
I have written the tests using viper but its not a big deal as the tests are only for checking whether the struct is being changed to the desired configuration.

**Comment by star-gazer111** [comment]
Resolved here #18
