### ISSUE TITLE
Implement `consensus/rpc`

### ISSUE THREAD

**Issue by gerceboss** [BlocSoc-iitr/selene#16]
Implement all the files inside `consensus/rpc` package

**Comment by x-senpai-x** [comment]
Assign

**Comment by x-senpai-x** [comment]
For mockRpc we need test data (Json files for bootstrap, finality , optimistic and updates) . So should I just implement the other 2 files?

**Comment by star-gazer111** [comment]
> For mockRpc we need test data (Json files for bootstrap, finality , optimistic and updates) . So should I just implement the other 2 files?

You can generate that testdata just like they did it here in [helios](https://github.com/a16z/helios/tree/b8cb0aa8412de356b8c88e283e028a6924111f37/consensus/testdata)

**Comment by x-senpai-x** [comment]
so I can just copy this data?

**Comment by x-senpai-x** [comment]
also Structs beaconblockdata,UpdateData,FinalityUpdateResponse,OptimisticUpdateResponse etc use data as structs defined in consensus core  in [helios](https://github.com/a16z/helios/blob/b8cb0aa8412de356b8c88e283e028a6924111f37/consensus-core/src/types/mod.rs#L32) so should I just assume they will be defined later on in selene and use them by name directly?

**Comment by gerceboss** [comment]
@x-senpai-x, for now, make a new file `consensus/consensus_core.go` and write the required structs there.

**Comment by x-senpai-x** [comment]
also why have we consensusRpc as struct field ? 
Shouldn't we just have rpc in the struct?

**Comment by star-gazer111** [comment]
Resolved here #21
