### ISSUE TITLE
Implement `consensus/types`

### ISSUE THREAD

**Issue by star-gazer111** [BlocSoc-iitr/selene#19]
Implement all the files inside the `consensus/types` package.

**Comment by star-gazer111** [comment]
@ABD-AZE u can start working on this issue now.

**Comment by ABD-AZE** [comment]
@star-gazer111 In the basic.go file, I don't think we require the ByteList struct as we can directly use [] byte. The transaction type can have the type [1073741824] bytes, with the ByteList type it would have dynamic size, which I think would not be efficient.

**Comment by star-gazer111** [comment]
@ABD-AZE what is the progress on this?

**Comment by ABD-AZE** [comment]
I'll try to complete it in a day or two

**Comment by star-gazer111** [comment]
> I'll try to complete it in a day or two

Incase, work on an issue takes longer than 4/5 days you can open up a PR & change it to a [draft](https://github.blog/news-insights/product-news/introducing-draft-pull-requests/) PR & keep working on it. You can later mark it as ready for review by following [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request)

**Comment by ABD-AZE** [comment]
@star-gazer111, utsav had already written these types in his PR. Only a few functions need to be defined. So I don't think we have to write these types i two different places we can go ahead with what utsav has alreayd implemented. Just the folder structure needs to adjusted as he has defined those types in consensus_core package within the consensus package. Please tell me how should I proceed?

**Comment by gerceboss** [comment]
ByteList is not needed to be reimplemented and same for common ones , jhst ensure the types are consistent.

**Comment by ABD-AZE** [comment]
Should I just copy paste what utsav has already implemented?

**Comment by star-gazer111** [comment]
Resolved here #25
