### ISSUE TITLE
Implement `common/types.go`

### ISSUE THREAD

**Issue by star-gazer111** [BlocSoc-iitr/selene#2]
- Prefer imports from geth or from any repository which is most starred rather than implementing from scratch.
- Maintain code layout.

**Comment by x-senpai-x** [comment]
interested

**Comment by x-senpai-x** [comment]
should I just create a transaction struct myself?

**Comment by star-gazer111** [comment]
> should I just create a transaction struct myself?

import it from some package of geth

**Comment by star-gazer111** [comment]
@x-senpai-x please open up a PR with your code asap and you can continue working on the same if it's not completed by then.

**Comment by star-gazer111** [comment]
Resolved here #11
