### ISSUE TITLE
Implement `consensus/types.go` & `consensus/database.go`

### ISSUE THREAD

**Issue by star-gazer111** [BlocSoc-iitr/selene#23]

**Comment by VeerChaurasia** [comment]
Assign

**Comment by star-gazer111** [comment]
@VeerChaurasia what are the updates on the progress so far?

**Comment by VeerChaurasia** [comment]
Almost completed.Just have a doubt do i need to implement ByteVectot too?

**Comment by star-gazer111** [comment]
> Almost completed.Just have a doubt do i need to implement bytevector too?

Where do u need that?

**Comment by VeerChaurasia** [comment]
I recently saw the updated beacon.go and basic.go wasn't it supposed to be completed by me?

**Comment by VeerChaurasia** [comment]
so should I just push the database.go?

**Comment by star-gazer111** [comment]
Resolved here #33
