### ISSUE TITLE
Implement `consensus/consensus.go`

### ISSUE THREAD

**Issue by star-gazer111** [BlocSoc-iitr/selene#24]

**Comment by DarkLord017** [comment]
assign please

**Comment by star-gazer111** [comment]
@DarkLord017 what are the updates on the progress so far?

**Comment by DarkLord017** [comment]
Completed half of the functions rest are pending (structs are done)... I'll complete it by today EOD 
sorry for late

**Comment by DarkLord017** [comment]
![image](https://github.com/user-attachments/assets/11070f1d-be92-46c4-b86d-9f0e39f5def1)
sir ye function helios me tha lekin networks.go me nhi hai 
![image](https://github.com/user-attachments/assets/b66efea6-f70a-47d2-890d-88d37d35a589)

**Comment by DarkLord017** [comment]
@star-gazer111

**Comment by star-gazer111** [comment]
@VeerChaurasia will create a new PR modifying networks.go by tomorrow. You can use it then.

**Comment by star-gazer111** [comment]
@DarkLord017 refer #35

**Comment by DarkLord017** [comment]
Okay

**Comment by DarkLord017** [comment]
@star-gazer111 sir done hai almost consensus_core me utils file nhi thi uske functions consensus.go me likhu ya consensus core me utils.go ek file bnayi hai uski PR alag se  kr du ?

**Comment by DarkLord017** [comment]
@star-gazer111 sir consensus.go me getpayload function define nahi hai lekin Helios me he aur uska use aa rha he to vo consensus me likhna he na ?
Aur sir tree hash root jo Helios me he vo library se le rhe hai to consensus.go me bhi koi library de dhundh ke import kar lu ?

**Comment by star-gazer111** [comment]
> @star-gazer111 sir consensus.go me getpayload function define nahi hai lekin Helios me he aur uska use aa rha he to vo consensus me likhna he na ? Aur sir tree hash root jo Helios me he vo library se le rhe hai to consensus.go me bhi koi library de dhundh ke import kar lu ?

- If any function was not defined initially but it's present in helios then u can define that yourself.
- Yes, import tree hash root from one of the packages of geth .

**Comment by DarkLord017** [comment]
> > @star-gazer111 sir consensus.go me getpayload function define nahi hai lekin Helios me he aur uska use aa rha he to vo consensus me likhna he na ? Aur sir tree hash root jo Helios me he vo library se le rhe hai to consensus.go me bhi koi library de dhundh ke import kar lu ?
> 
> * If any function was not defined initially but it's present in helios then u can define that yourself.
> * Yes, import tree hash root from one of the packages of geth .

Okay sir

**Comment by star-gazer111** [comment]
> > @star-gazer111 sir consensus.go me getpayload function define nahi hai lekin Helios me he aur uska use aa rha he to vo consensus me likhna he na ? Aur sir tree hash root jo Helios me he vo library se le rhe hai to consensus.go me bhi koi library de dhundh ke import kar lu ?
> 
> * If any function was not defined initially but it's present in helios then u can define that yourself.
> * Yes, import tree hash root from one of the packages of geth .

@DarkLord017 also, before defining anything in a new types.go please do check if we have already defined it somewhere in common or config module so we don't rewrite same thing again.

**Comment by DarkLord017** [comment]
okay sir

**Comment by VeerChaurasia** [comment]
@DarkLord017 do you need ChainID function and Baseconfig function(defined in networks.go) outside the package of config ?

**Comment by star-gazer111** [comment]
Resolved here #51 .
