### ISSUE TITLE
Implement `execution/constants.go` & `execution/execution.go`

### ISSUE THREAD

**Issue by star-gazer111** [BlocSoc-iitr/selene#28]

**Comment by ABD-AZE** [comment]
Assign please

**Comment by star-gazer111** [comment]
@ABD-AZE what are the updates on the progress?

**Comment by ABD-AZE** [comment]
Not much progress has been made, I'll try to open the PR by the weekend.

**Comment by ABD-AZE** [comment]
@star-gazer111 , @gerceboss

**Comment by star-gazer111** [comment]
@ABD-AZE can you please implement `execution/rpc` as well and raise a new PR for that?
You can then import the necessary functionalities for this issue from that PR.

**Comment by ABD-AZE** [comment]
@star-gazer111 sure, I'll start it right away, give me some time.

**Comment by star-gazer111** [comment]
Resolved here #80 & #81
