### ISSUE TITLE
Implement `execution/state.go` & `execution/types.go`

### ISSUE THREAD

**Issue by star-gazer111** [BlocSoc-iitr/selene#31]

**Comment by VeerChaurasia** [comment]
assign

**Comment by VeerChaurasia** [comment]
@star-gazer111 I have almost completed this should I make a pr(I have changed common/types.go as it was needed for state.go basically the structs were not exportable)

**Comment by star-gazer111** [comment]
> @star-gazer111 I have almost completed this should I make a pr(I have changed common/types.go as it was needed for state.go basically the structs were not exportable)

can you make a separate PR for each?

**Comment by star-gazer111** [comment]
Resolved here #42
