### ISSUE TITLE
Add `StateDB` implementation

### ISSUE THREAD

**Issue by gerceboss** [BlocSoc-iitr/selene#68]
- Add [statedb](https://github.com/ethereum/go-ethereum/blob/master/core/state/statedb.go) present in Geth by making a package `statedb` inside package `execution`
- Try importing it first , if that works we don't need to copy this whole file and its dependencies

**Comment by 18aaddy** [comment]
Assign pls

**Comment by star-gazer111** [comment]
we continued with proofDB as in helios, so this can be closed in favour of EVM package
