### ISSUE TITLE
fix NewConsensusClient() function

### ISSUE THREAD

**Issue by 18aaddy** [BlocSoc-iitr/selene#77]
#### Summary
There are some errors in the New function for Consensus Client struct. Here is the summary for the issues:
- Consensus Client fields, `BlockRecv` and `FinalizedBlockRecv` are of wrong types
- There is a problem in the way database is created in the `New()` function for ConsensusClient
- There is a problem in the way `config.Checkpoint` is handled in the `New()` function

#### Detailed Description
1. The Consensus Client struct has fields `BlockRecv` and `FinalizedBlockRecv` which were initially of type common.Block or a pointer to it. They need to be of types `chan *common.Block` as `NewState()` function takes inputs `chan *common.Block` so that we can continuously send blocks as they are fetched from the rpc and update the state periodically.

2. There is a problem in the way database was used in the `New()` function for consensus client. It was of types interface, not any concrete type, so when `db.New()` function was called, it was giving rise to an `invalid address or nil pointer dereference` error.

3.    Finally, There is a problem in the way `config.Checkpoint` is handled in the New() function. It would see if the user had assigned some value to config.Checkpoint, and then it would instead load a value from the db and assign that instead. The correct way , as given in Helios, would be to check if the user had not assigned a value, to load a value from the db and if there is an error in loading, use the default checkpoint value.

**Comment by star-gazer111** [comment]
Resolved here #78
