### ISSUE TITLE
bug: function `CreateAccessList()` is not working

### ISSUE THREAD

**Issue by 18aaddy** [BlocSoc-iitr/selene#89]
In `execution/http_rpc.go`, the function `CreateAccessList()` is throwing an error. It is not able to unmarshal data from the rpc to `types.AccessList` struct.

**Comment by 18aaddy** [comment]
@ABD-AZE  can you try and fix this? You can use the tests from PR #88

**Comment by ABD-AZE** [comment]
The type accesslist needs to be changed, @x-senpai-x has defined the new type in evm.go. Once he changes the type I'll look into this.

**Comment by gerceboss** [comment]
@ABD-AZE please be quick as there are 2 PRs that require this code to be merged first

**Comment by ABD-AZE** [comment]
I'll do it by EOTD

**Comment by 18aaddy** [comment]
@gerceboss I think my PR #88 for http_rpc test might need to be merged first and this should be afterwards. I have modified the http_rpc file so that every other test passes and then the CreateAccessList function can be modified so that TestCreateAccessList passes

**Comment by 18aaddy** [comment]
Resolved here #107
